Fix test scripts

diff --git a/utils/fuzz-test b/utils/fuzz-test
--- a/utils/fuzz-test
+++ b/utils/fuzz-test
@@ -67,20 +67,20 @@ jpeg_pattern=$prefix/*.$JPEG_EXTENSION
 ycc_pattern=$prefix/*.$YCC_EXTENSION
 
 check   "error: swift build failed" \
-        swift build -c $build_configuration --product fuzzer
+        swift build -c $build_configuration --product JPEG-fuzzer
 check   "error: swift build failed" \
-        swift build -c $build_configuration --product comparator
+        swift build -c $build_configuration --product JPEG-comparator
 
 binaries=".build/$build_configuration"
-if ! [ -f $binaries/fuzzer ]; then
-    error "error: missing fuzzer tool"
+if ! [ -f $binaries/JPEG-fuzzer ]; then
+    error "error: missing JPEG-fuzzer tool"
 fi
 
 mkdir   $prefix         &> /dev/null
 rm      $jpeg_pattern   &> /dev/null
 
 check   "error: test image generation failed" \
-        $binaries/fuzzer --count $count --path $prefix
+        $binaries/JPEG-fuzzer --count $count --path $prefix
 
 rm      $ycc_pattern    &> /dev/null
 
@@ -89,4 +89,4 @@ for file in $jpeg_pattern ; do
             convert -depth 8 -define jpeg:dct-method=float "jpeg:$file" "ycbcr:$file.$YCC_EXTENSION"
 done 
 
-$binaries/comparator $jpeg_pattern
+$binaries/JPEG-comparator $jpeg_pattern
